### ISSUE TITLE
Group common functions into helpers

### ISSUE THREAD

**Issue by mudler** [SUSE/catapult#41] opened 2019-10-02 06:32 UTC
There are common usages and patterns that can be identified in the current script ( a lot of dup code to do kube calls! ).

We could group them e.g. into functions, split in helpers (even by category) that can be included when necessary. During refactoring, they should come with unit tests whenever possible

Relates to https://github.com/SUSE/catapult/issues/35

**Comment by viccuad** [comment] 2019-12-13 12:55
Closing as duplicate of #90. Leaving #90, which is newer, but is already linked to others.

**Closed by viccuad** 2019-12-13 12:55 UTC
