### ISSUE TITLE
Some kubecf resources not cleaned up by `make scf-clean`

### ISSUE THREAD

**Issue by HartS** [SUSE/catapult#128] opened 2020-03-13 13:21 UTC
Testing kubecf deployments via catapult, when I clean a kubecf cluster with `make scf-clean`, and attempt to redeploy with `make scf`, I'll encounter this error:

```
Installing CFO from: https://s3.amazonaws.com/cf-operators/release/helm-charts/cf-operator-3.2.1%2B0.ga32a3f79.tgz
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: cf-operator-quarks-job, existing_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole, new_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole
Makefile:17: recipe for target 'install' failed
```

I found I have to delete the CR and CRBs manually with the following commands before I can deploy again:

```
kubectl delete clusterrolebinding cf-operator cf-operator-quarks-job
kubectl delete clusterrole cf-operator-quarks-job cf-operator
```

And in a previous reinstall, I also had to run:
```
kubectl delete psp susecf-scf-default
```
(though I didn't see this psp lingering after the last clean)

**Comment by viccuad** [comment] 2020-03-13 14:21
Thanks for reporting this!

I can reproduce this, and the cap-release pipeline too.

This was not picked up by the kubecf pipeline because they spawn kind clusters, use them, and then get rid of them.

Apart from those changes, once one configures kubecf to deploy with the qjobs for testsuites, with `SCF_TESTGROUP=true` (see modules/scf/gen-config.sh), it is needed to remove these too, and maybe more for all testsuites:

```
kubectl delete clusterrole scf-susecf-scf-test-cluster-role || true                                                                                                                                                  
kubectl delete clusterrolebinding \                                                                                                                                                                                  
        scf-susecf-scf-tests-brain-test-cluster-role-cluster-binding || true                                                                                                                                         
kubectl delete clusterrolebinding \                                                                                                                                                                                  
        scf-susecf-scf-tests-sits-test-cluster-role-cluster-binding || true 
```

I have removed them by hand and redeployed, and weirdly kubecf complains on deployment that they exist. It is like the kubecf helm chart adds them twice, and then complains it exists.


All these deletions could be added to `modules/scf/clean.sh`, do you feel like tackling it?

**Comment by viccuad** [comment] 2020-03-16 11:30
When doing https://github.com/SUSE/catapult/pull/135 it seems that helm3 doesn't do a --wait anymore, so one needs to do `make scf-clean`, wait a bit, `make scf` as workaround. This should be fixed for the pipelines, though.

**Comment by viccuad** [comment] 2020-03-26 07:17
I haven't hit `clusterrole` and `clusterrolebinding` being still present with kubecf-v1.0.0.

The problem of helm not blocking and waiting when deleting cf-operator and scf persists.

**Closed** 2020-04-03 14:09 UTC
Labels: priority: critical
